import './css/style.css'
import { GoogleAnalytics } from '@next/third-parties/google'

import { Inter, Playfair_Display } from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
})

const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair-display',
  display: 'swap'
})

// export const metadata = {
//   title: 'Innovapath',
//   description: 'Generated by create next app',
// }
export const metadata = {
  title: 'Innovapath',
  description: 'Generated by create next app',
  icons: {
    icon: [
      {
        url: '/faviconold.png',
        type: 'image/png',
        sizes: '500x500',
      },
    ],
    apple: {
      url: '/faviconold.png',
      type: 'image/png',
      sizes: '500x500',
    },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${playfair.variable} font-inter antialiased bg-white text-slate-800 tracking-tight`}>
        {children}
        <GoogleAnalytics gaId="G-XXXXXXXXXX" />
      </body>
    </html>
  )
}
